# fly --target=tutorial login --concourse-url=http://127.0.0.1:8080 --username=test --password=test
# fly --target=tutorial set-pipeline -p push-docker-image -c pipeline.yml -n

# kubectl rollout restart deployment myapp

resources:
- name: tutorial
  type: git
  source:
    uri: https://github.com/drnic/concourse-tutorial.git
    branch: develop

- name: hello-world-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/((docker-hub-repository))

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: tutorial
  - put: hello-world-docker-image
    params:
      build: tutorial/tutorials/miscellaneous/docker-images/docker