version: "3.7"

services:
  d1:
    image: node:16-alpine3.14
    container_name: d1
    ports:
      - 7050:7050
    volumes:
      - ./docker1.js:/app/server.js
    working_dir: /app
    command: node server.js

  d2:
    image: node:16-alpine3.14
    container_name: d2
    ports:
      - 7051:7051
    volumes:
      - ./docker2.js:/app/server.js
    working_dir: /app
    command: node server.js

  web: #192.168.225.139
    image: nginx:1.17
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker cp nginx:/etc/nginx/conf.d/default.conf ./default.conf
# docker-compose up -d web
# docker exec -it nginx nginx -t
# docker exec -it nginx nginx -s reload