version: "3.1"

services:
  postgresdb:
    image: postgres:14
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - liquibaseNet

  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8001:80
    networks:
      - liquibaseNet
    depends_on:
      - postgresdb

  liquibase:
    image: liquibase/liquibase:4.21.1
    container_name: liquibase
    environment:
      #INSTALL_MYSQL: true
      LIQUIBASE_LOG_LEVEL: DEBUG
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgresdb:5432/mydb #?currentSchema="myschema"
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: changeme
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: public
    command: --changelog-file=config/changelog.xml update
    # command: --logLevel=DEBUG --defaultsFile=config/liquibase.properties --changeLogFile=config/changelog.xml update
    volumes:
      - ./config:/liquibase/config
    networks:
      - liquibaseNet
    # entrypoint: tail -f /dev/null
    depends_on:
      - postgresdb

networks:
  liquibaseNet: